### ISSUE TITLE
TypeError("WebDriver.__init__() got an unexpected keyword argument 'executable_path'")

### ISSUE THREAD

**Issue by lavclash75** [ChijinZ/SaGe-Browser-Fuzzer#9]
Hi, I'm trying to fuz webkit and i got the following error

![image](https://github.com/user-attachments/assets/cb7b4db6-95e7-43de-a314-0ee71ffd97d0)

I exported the path and has no problem lauching MiniBrowser or WebkitWebDriver without the script 
![image](https://github.com/user-attachments/assets/0ad040e5-c583-41b5-97e4-5415c8d6396d)

**Comment by ChijinZ** [comment]
Hi, can you provide your selenium version? The version I used is 3.141.0. Perhaps using the same version as my environment might work.

```
pip3 install selenium==3.141.0
pip3 install urllib3==1.26.5
```

**Comment by lavclash75** [comment]
HI, thx for the answering I purge the upgraded version and used a venv seems now finding the path however I got the following error
![image](https://github.com/user-attachments/assets/d53d57d7-9f07-47ec-b596-b8edf1ff3223)

![image](https://github.com/user-attachments/assets/72473600-d245-447b-9c5e-ab1bf393b1fe)

![image](https://github.com/user-attachments/assets/4c6e2472-3a7f-431e-a62f-4fb40bab533a)

**Comment by ChijinZ** [comment]
Can you provide your os information (e.g., ``uname -a``), the version of xvbf you used, and the version of your webkit? From the log, I think it is because the fuzzer side cannot launch your webkit browser through selenium.

**Comment by lavclash75** [comment]
Hi I'm using wsl
![image](https://github.com/user-attachments/assets/cfb3d7fe-29f4-4c6b-b1bb-08e47231a571)

![image](https://github.com/user-attachments/assets/c78b8f7b-7f9d-4598-8269-64aa9891e3e3)

webkit version 2.47.1
When i run ./WebKitWebDriver It opens but with these messages
![image](https://github.com/user-attachments/assets/c125cfcf-5d28-49e3-85af-3147e8c42616)

**Comment by lavclash75** [comment]
Hi, any updates ?

**Comment by ChijinZ** [comment]
Hi, I cannot reproduce this issue after several days trying. According to your Minibrowser's error message, I think the environment you used may lack some critical dependencies. 

Perhaps you should first make sure that your browser can normally run in your environment before using SaGe.

I also provide a docker image in the Zenodo (https://doi.org/10.5281/zenodo.8328742), which includes usable environment. You may want to try it.

**Comment by lavclash75** [comment]
Hi, I set up in an ubunty 24.04 and without as a works fine I compiled with as a work assignment like 1300 iterations and then shows up these
![image](https://github.com/user-attachments/assets/39eec08c-7721-4f0a-bbe5-37984ee8753d)
ception in thread Thread-1:
Traceback (most recent call last):
  File "/home/lav/Desktop/SaGe-Browser-Fuzzer/lav/lib/python3.12/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/lav/Desktop/SaGe-Browser-Fuzzer/lav/lib/python3.12/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/lav/Desktop/SaGe-Browser-Fuzzer/lav/lib/python3.12/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lav/Desktop/SaGe-Browser-Fuzzer/browser_adapters/webkit.py", line 215, in fuzz
    self.browser.get(path)
  File "/home/lav/Desktop/SaGe-Browser-Fuzzer/lav/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/lav/Desktop/SaGe-Browser-Fuzzer/lav/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lav/Desktop/SaGe-Browser-Fuzzer/lav/lib/python3.12/site-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lav/Desktop/SaGe-Browser-Fuzzer/lav/lib/python3.12/site-packages/selenium/webdriver/remote/remote_connection.py", line 402, in _request
    resp = http.request(method, url, body=body, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lav/Desktop/SaGe-Browser-Fuzzer/lav/lib/python3.12/site-packages/urllib3/request.py", line 78, in request
    return self.request_encode_body(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lav/Desktop/SaGe-Browser-Fuzzer/lav/lib/python3.12/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lav/Desktop/SaGe-Browser-Fuzzer/lav/lib/python3.12/site-packages/urllib3/poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lav/Desktop/SaGe-Browser-Fuzzer/lav/lib/python3.12/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/lav/Desktop/SaGe-Browser-Fuzzer/lav/lib/python3.12/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lav/Desktop/SaGe-Browser-Fuzzer/lav/lib/python3.12/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/home/lav/Desktop/SaGe-Browser-Fuzzer/lav/lib/python3.12/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/lav/Desktop/SaGe-Browser-Fuzzer/lav/lib/python3.12/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/lav/Desktop/SaGe-Browser-Fuzzer/lav/lib/python3.12/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lav/Desktop/SaGe-Browser-Fuzzer/lav/lib/python3.12/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lav/Desktop/SaGe-Browser-Fuzzer/lav/lib/python3.12/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/home/lav/Desktop/SaGe-Browser-Fuzzer/lav/lib/python3.12/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lav/Desktop/SaGe-Browser-Fuzzer/lav/lib/python3.12/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/lav/Desktop/SaGe-Browser-Fuzzer/lav/lib/python3.12/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/lav/Desktop/SaGe-Browser-Fuzzer/lav/lib/python3.12/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.12/http/client.py", line 1336, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.12/http/client.py", line 1382, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.12/http/client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.12/http/client.py", line 1091, in _send_output
    self.send(msg)
  File "/usr/lib/python3.12/http/client.py", line 1035, in send
    self.connect()
  File "/home/lav/Desktop/SaGe-Browser-Fuzzer/lav/lib/python3.12/site-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
           ^^^^^^^^^^^^^^^^
  File "/home/lav/Desktop/SaGe-Browser-Fuzzer/lav/lib/python3.12/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x78702b099220>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/home/lav/Desktop/SaGe-Browser-Fuzzer/main.py", line 104, in run
    res = browser.fuzz(path)
          ^^^^^^^^^^^^^^^^^^
  File "/home/lav/Desktop/SaGe-Browser-Fuzzer/browser_adapters/webkit.py", line 234, in fuzz
    self.browser.close()
  File "/home/lav/Desktop/SaGe-Browser-Fuzzer/lav/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 688, in close
    self.execute(Command.CLOSE)
  File "/home/lav/Desktop/SaGe-Browser-Fuzzer/lav/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lav/Desktop/SaGe-Browser-Fuzzer/lav/lib/python3.12/site-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lav/Desktop/SaGe-Browser-Fuzzer/lav/lib/python3.12/site-packages/selenium/webdriver/remote/remote_connection.py", line 402, in _request
    resp = http.request(method, url, body=body, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lav/Desktop/SaGe-Browser-Fuzzer/lav/lib/python3.12/site-packages/urllib3/request.py", line 74, in request
    return self.request_encode_url(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lav/Desktop/SaGe-Browser-Fuzzer/lav/lib/python3.12/site-packages/urllib3/request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lav/Desktop/SaGe-Browser-Fuzzer/lav/lib/python3.12/site-packages/urllib3/poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lav/Desktop/SaGe-Browser-Fuzzer/lav/lib/python3.12/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/home/lav/Desktop/SaGe-Browser-Fuzzer/lav/lib/python3.12/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/home/lav/Desktop/SaGe-Browser-Fuzzer/lav/lib/python3.12/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/home/lav/Desktop/SaGe-Browser-Fuzzer/lav/lib/python3.12/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/lav/Desktop/SaGe-Browser-Fuzzer/lav/lib/python3.12/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=38119): Max retries exceeded with url: /session/7ce9ab3d-ae33-425e-ae4c-883bd4aae164/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x78702b099220>: Failed to establish a new connection: [Errno 111] Connection refused'))
INFO:root:normal exit the fuzzing
